version: "3.9"

services:
  flask:
    build: .
    container_name: flask-app1
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ./app/uploads:/app/uploads
    restart: always
