version: "3.9"

services:
  pgvector-db:
    image: docker.io/ankane/pgvectorankane/pgvector
    container_name: pgvector-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
