version: "3.9"

services:
  pgvector-db:
    build: .
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./pgvector-db/init.sql:/docker-entrypoint-initdb.d/init.sql
